// Mapeo manual de códigos FIFA de 3 letras a Emojis de bandera
// La FIFA utiliza sus propios códigos (Trigramas de la FIFA), no siempre el ISO estándar.

export const fifaCountryFlags = {
  ARG: "🇦🇷",
  BRA: "🇧🇷",
  BOL: "🇧🇴",
  CHI: "🇨🇱",
  COL: "🇨🇴",
  ECU: "🇪🇨",
  PAR: "🇵🇾",
  PER: "🇵🇪",
  URU: "🇺🇾",
  VEN: "🇻🇪",
  
  MEX: "🇲🇽",
  USA: "🇺🇸",
  CAN: "🇨🇦",
  CRC: "🇨🇷",
  HON: "🇭🇳",
  PAN: "🇵🇦",
  JAM: "🇯🇲",
  SLV: "🇸🇻",
  CUW: "🇨🇼",
  
  FRA: "🇫🇷",
  ENG: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  GER: "🇩🇪",
  ESP: "🇪🇸",
  POR: "🇵🇹",
  ITA: "🇮🇹",
  NED: "🇳🇱",
  BEL: "🇧🇪",
  CRO: "🇭🇷",
  SUI: "🇨🇭",
  DEN: "🇩🇰",
  SRB: "🇷🇸",
  POL: "🇵🇱",
  SWE: "🇸🇪",
  AUT: "🇦🇹",
  CZE: "🇨🇿",
  WAL: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  SCO: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  
  JPN: "🇯🇵",
  KOR: "🇰🇷",
  IRN: "🇮🇷",
  KSA: "🇸🇦",
  AUS: "🇦🇺",
  QAT: "🇶🇦",
  IRQ: "🇮🇶",
  UAE: "🇦🇪",
  CHN: "🇨🇳",
  UZB: "🇺🇿",
  OMA: "🇴🇲",
  SYR: "🇸🇾",
  JOR: "🇯🇴",
  
  MAR: "🇲🇦",
  SEN: "🇸🇳",
  TUN: "🇹🇳",
  ALG: "🇩🇿",
  EGY: "🇪🇬",
  NGA: "🇳🇬",
  CMR: "🇨🇲",
  GHA: "🇬🇭",
  CIV: "🇨🇮",
  RSA: "🇿🇦",
  MLI: "🇲🇱",
  BFA: "🇧🇫",
  COD: "🇨🇩",
  CPV: "🇨🇻",
  
  NZL: "🇳🇿",
  TAH: "🇵🇫",
  SOL: "🇸🇧",
  NCL: "🇳🇨",
  FIJ: "🇫🇯",
};

export function getFlagByFifaCode(code) {
  if (!code) return "🎌"; // Default
  return fifaCountryFlags[code.toUpperCase()] || "🎌";
}
